services:
  # POSTGRES DATABASE 
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orglog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis message queue 
  redis: 
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  # FastAPI server 
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/orglog
      JWT_SECRET: ORGLOG_SECRET_KEY
    depends_on:
      - postgres
      - redis 

  # log worker 
  worker:
    build: .
    command: python -m app.workers.log_worker
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/orglog
      JWT_SECRET: ORGLOG_SECRET_KEY
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
